airbnb_analytics:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: workspace
      schema: airbnb  
      host: dbc-bf88daea-a04e.cloud.databricks.com
      http_path: /sql/1.0/warehouses/8b8af9d912dae651
      token: dapi752551efb8e89c8911e55821d35e3a78
      threads: 4
      
    prod:
      type: databricks
      catalog: workspace
      schema: airbnb
      host: dbc-bf88daea-a04e.cloud.databricks.com
      http_path: /sql/1.0/warehouses/8b8af9d912dae651
      token: dapi752551efb8e89c8911e55821d35e3a78
      threads: 8